### PR TITLE
#Todo-list-project

### PR DESCRIPTION
**Pull request by codecell**
**What does this PR do?**
- This is for TSE review of the project implementation.

Live version [here](https://smithvyne.github.io/JS-TodoList/)

**How can this be manually tested?**
- After cloning the project
2. Navigate to the project directory `cd JS-TodoList`.
3. Install project dependencies `npm install`
4. Run `npm run dev` to compile a development build.
5. Run `npm run start` to serve the project live on `http://localhost:9000` and voila!!!.

**Project specs**
- https://www.theodinproject.com/courses/javascript/lessons/todo-list

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Your UI looks nice! :+1: However, there are some issues I'd like you to work on before moving forward. These are:
- [ ] I am unable to create/edit/delete todo items for any given project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] For your `installation` instructions in your `README.md` file, `npm run webpack` doesn't work since it isn't part of your script's commands in the the `package.json` file. Please change it to the appropriate command.
- [ ] __[Optional]__ I have to close the dialog window for creating projects after I have created a project in order to have it disappear so that I can view my created project. It would be better if this window disappears once I create a new project.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by codecell** [comment]
> ### Changes Required! ♻️
> Hi team! Your UI looks nice! 👍 However, there are some issues I'd like you to work on before moving forward. These are:
> 
> * [ ]  I am unable to create/edit/delete todo items for any given project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
> * [ ]  For your `installation` instructions in your `README.md` file, `npm run webpack` doesn't work since it isn't part of your script's commands in the the `package.json` file. Please change it to the appropriate command.
> * [ ]  **[Optional]** I have to close the dialog window for creating projects after I have created a project in order to have it disappear so that I can view my created project. It would be better if this window disappears once I create a new project.
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> **Treasure Kabareebe**
> [GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by codecell** [comment]
Hi @trekab , All the CRUD were all implemented and are working perfectly fine.

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Congratulations team! Well done meeting the project requirements. Keep up the good work!

__[Note]__: Initially the required functionality wasn't working on my end. Probably my browser had some issues I am trying to figure out now. Sorry for the inconvenience and thanks for reaching out about this. :pray: 

__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
